export const FIRST_NAME_VALID = 'FIRST_NAME_VALID'
export const FIRST_NAME_NOT_VALID = 'FIRST_NAME_NOT_VALID'

export const LAST_NAME_VALID = 'LAST_NAME_VALID'
export const LAST_NAME_NOT_VALID = 'LAST_NAME_NOT_VALID'

export const EMAIL_VALID = 'EMAIL_VALID'
export const EMAIL_NOT_VALID = 'EMAIL_NOT_VALID'

export const PHONE_VALID = 'PHONE_VALID'
export const PHONE_NOT_VALID = 'PHONE_NOT_VALID'